server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_6
    username: mushroom
    password: the_burglar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

logging:
  level:
    org.springframework: INFO
